# populate this config. structure
# we will populate the agent body config with this

agent:
  history: 2
  h_dim: 8
  z_dim: 8
  a_dim: 8
  state_depth: 3
  device: cuda
  batch_size: ${env.PLAYER_N}
  inference_steps: 25
  param_learning_steps: 5
  atomic_timestep: 2
  discrete_step: 2
  history_size: ${eval:"${agent.atomic_timestep} * ${agent.history}"}
  discrete_timestep: ${eval:"${agent.atomic_timestep} * ${agent.discrete_step}"}

  nmmo_obs_encoder:
    name: NmmoEncoders
    intermediate: 32
    hidden_size: ${agent.z_dim}
    device: ${agent.device}

  nmmo_obs_decoder:
    name: NmmoDecoders
    intermediate: 32
    hidden_size: ${agent.z_dim}
    device: ${agent.device}

  NmmoObsAE:
    encoder: ${agent.nmmo_obs_encoder}
    decoder: ${agent.nmmo_obs_decoder}

  zAE:
    obs_hid_size: ${agent.nmmo_obs_encoder.hidden_size}
    z_dim: ${agent.z_dim}

  latent_az_encoder:
    az_dim: ${eval:"${agent.z_dim} + ${agent.a_dim}"}

  latent_az_decoder:
    az_dim: ${eval:"${agent.z_dim} + ${agent.a_dim}"}

  transition_model:
    latent_az_encoder: ${agent.latent_az_encoder}
    latent_az_decoder: ${agent.latent_az_decoder}
    recurrence_type: transformer
    cache_keep_len: ${agent.atomic_timestep}
    hidsize: ${agent.h_dim}
    n_recurrence_layers: ${agent.state_depth}
    atomic_size: ${agent.atomic_timestep}
    batch_size: ${agent.batch_size}
    device: ${agent.device}

  grounding_wm:
    latent_az_encoder: ${agent.latent_az_encoder}
    latent_az_decoder: ${agent.latent_az_decoder}
    recurrence_type: transformer
    cache_keep_len: ${eval:"${agent.history_size} + ${agent.discrete_timestep} + ${agent.atomic_timestep}"} # + 1 atomic to include the first state we passed in.
    hidsize: ${agent.h_dim}
    n_recurrence_layers: ${agent.state_depth}
    atomic_size: ${agent.atomic_timestep}
    batch_size: ${agent.batch_size}
    device: ${agent.device}


  

env:
  ALLOW_MOVE_INTO_OCCUPIED_TILE: True
  ALLOW_MULTI_TASKS_PER_AGENT: False
  COMBAT_ALLOW_FLEXIBLE_STYLE: True
  COMBAT_MAGE_DAMAGE: 10
  COMBAT_MAGE_REACH: 3
  COMBAT_MELEE_DAMAGE: 10
  COMBAT_MELEE_REACH: 3
  COMBAT_MINIMUM_DAMAGE_PROPORTION: 0.25
  COMBAT_RANGE_DAMAGE: 10
  COMBAT_RANGE_REACH: 3
  COMBAT_SPAWN_IMMUNITY: 20
  COMBAT_STATUS_DURATION: 3
  COMBAT_SYSTEM_ENABLED: True
  COMBAT_WEAKNESS_MULTIPLIER: 1.5
  COMMUNICATION_NUM_TOKENS: 127
  COMMUNICATION_N_OBS: 32
  COMMUNICATION_SYSTEM_ENABLED: True
  DEATH_FOG_FINAL_SIZE: 8
  DEATH_FOG_SPEED: 1
  EQUIPMENT_AMMUNITION_BASE_DAMAGE: 5
  EQUIPMENT_AMMUNITION_LEVEL_DAMAGE: 10
  EQUIPMENT_ARMOR_BASE_DEFENSE: 0
  EQUIPMENT_ARMOR_LEVEL_DEFENSE: 3
  EQUIPMENT_SYSTEM_ENABLED: True
  EQUIPMENT_TOOL_BASE_DEFENSE: 15
  EQUIPMENT_TOOL_LEVEL_DEFENSE: 0
  EQUIPMENT_WEAPON_BASE_DAMAGE: 5
  EQUIPMENT_WEAPON_LEVEL_DAMAGE: 5
  EXCHANGE_BASE_GOLD: 1
  EXCHANGE_LISTING_DURATION: 3
  EXCHANGE_SYSTEM_ENABLED: True
  HORIZON: 1000000
  IMMORTAL: True
  ITEM_ALLOW_GIFT: True
  ITEM_INVENTORY_CAPACITY: 12
  ITEM_N: 17
  ITEM_SYSTEM_ENABLED: True
  MAP_CENTER: 128
  MAP_FORCE_GENERATION: True
  MAP_GENERATE_PREVIEWS: False
  MAP_N: 1
  MAP_N_TILE: 16
  MAP_PREVIEW_DOWNSCALE: 4
  MAP_RESET_FROM_FRACTAL: True
  MAP_SIZE: 160
  MARKET_N_OBS: 384
  MAX_HORIZON: 1000001
  NPC_ALLOW_ATTACK_OTHER_NPCS: False
  NPC_BASE_DAMAGE: 0
  NPC_BASE_DEFENSE: 0
  NPC_DEFAULT_REFILL_DEAD_NPCS: True
  NPC_LEVEL_DAMAGE: 8
  NPC_LEVEL_DEFENSE: 8
  NPC_LEVEL_MAX: 10
  NPC_LEVEL_MIN: 1
  NPC_LEVEL_MULTIPLIER: 1.0
  NPC_LEVEL_SPREAD: 1
  NPC_N: 128
  NPC_SPAWN_AGGRESSIVE: 0.8
  NPC_SPAWN_ATTEMPTS: 25
  NPC_SPAWN_NEUTRAL: 0.5
  NPC_SPAWN_PASSIVE: 0.0
  NPC_SYSTEM_ENABLED: True
  PLAYER_BASE_HEALTH: 100
  PLAYER_HEALTH_INCREMENT: 0
  PLAYER_N: 1
  PLAYER_N_OBS: 100
  PLAYER_VISION_RADIUS: 7
  PRICE_N_OBS: 99
  PROFESSION_CRYSTAL_CAPACITY: 1
  PROFESSION_CRYSTAL_RESPAWN: 0.1
  PROFESSION_FISH_CAPACITY: 1
  PROFESSION_FISH_RESPAWN: 0.02
  PROFESSION_HERB_CAPACITY: 1
  PROFESSION_HERB_RESPAWN: 0.02
  PROFESSION_ORE_CAPACITY: 1
  PROFESSION_ORE_RESPAWN: 0.1
  PROFESSION_SYSTEM_ENABLED: True
  PROFESSION_TREE_CAPACITY: 1
  PROFESSION_TREE_RESPAWN: 0.105
  PROGRESSION_AMMUNITION_XP_SCALE: 15
  PROGRESSION_BASE_DEFENSE: 0
  PROGRESSION_BASE_LEVEL: 1
  PROGRESSION_COMBAT_XP_SCALE: 6
  PROGRESSION_CONSUMABLE_XP_SCALE: 30
  PROGRESSION_EXP_THRESHOLD: [0, 90, 217, 373, 553, 754, 974, 1212, 1467, 1737]
  PROGRESSION_LEVEL_DEFENSE: 5
  PROGRESSION_LEVEL_MAX: 10
  PROGRESSION_MAGE_BASE_DAMAGE: 10
  PROGRESSION_MAGE_LEVEL_DAMAGE: 5
  PROGRESSION_MELEE_BASE_DAMAGE: 10
  PROGRESSION_MELEE_LEVEL_DAMAGE: 5
  PROGRESSION_RANGE_BASE_DAMAGE: 10
  PROGRESSION_RANGE_LEVEL_DAMAGE: 5
  PROGRESSION_SPAWN_CLUSTERS: 64
  PROGRESSION_SPAWN_UNIFORMS: 256
  PROGRESSION_SYSTEM_ENABLED: True
  PROVIDE_ACTION_TARGETS: True
  PROVIDE_DEATH_FOG_OBS: False
  PROVIDE_NOOP_ACTION_TARGET: True
  RESOURCE_BASE: 100
  RESOURCE_DAMAGE_REDUCTION: 0.5
  RESOURCE_DEHYDRATION_RATE: 10
  RESOURCE_DEPLETION_RATE: 5
  RESOURCE_FOILAGE_CAPACITY: 1
  RESOURCE_FOILAGE_RESPAWN: 0.025
  RESOURCE_HARVEST_RESTORE_FRACTION: 1.0
  RESOURCE_HEALTH_REGEN_THRESHOLD: 0.5
  RESOURCE_HEALTH_RESTORE_FRACTION: 0.1
  RESOURCE_RESILIENT_POPULATION: 0
  RESOURCE_STARVATION_RATE: 10
  RESOURCE_SYSTEM_ENABLED: True
  TASK_EMBED_DIM: 4096
  TERRAIN_DISABLE_STONE: False
  TERRAIN_FLIP_SEED: False
  TERRAIN_FOILAGE: 0.85
  TERRAIN_FREQUENCY: -3
  TERRAIN_FREQUENCY_OFFSET: 7
  TERRAIN_GRASS: 0.7
  TERRAIN_LOG_INTERPOLATE_MAX: 0
  TERRAIN_LOG_INTERPOLATE_MIN: 0
  TERRAIN_RESET_TO_GRASS: False
  TERRAIN_SCATTER_EXTRA_RESOURCES: True
  TERRAIN_SYSTEM_ENABLED: True
  TERRAIN_TILES_PER_OCTAVE: 8
  TERRAIN_VOID: 0.0
  TERRAIN_WATER: 0.3
  USE_CYTHON: True
  WEAPON_DROP_PROB: 0.025

